# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_block_file <- function(block_file) {
    .Call(`_MR_LDP_load_block_file`, block_file)
}

test_blocks <- function(bp, chr, block_file) {
    .Call(`_MR_LDP_test_blocks`, bp, chr, block_file)
}

Cal_blockR <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, coreNum, lam) {
    .Call(`_MR_LDP_Cal_blockR`, bp, chr, avbIndex, idx4panel, block_file, stringname3, coreNum, lam)
}

Cal_block_Rmatrix <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, coreNum, lam) {
    .Call(`_MR_LDP_Cal_block_Rmatrix`, bp, chr, avbIndex, idx4panel, block_file, stringname3, coreNum, lam)
}

gibbs2_update_gamma <- function(gammah, Gammah, sg2, sG2, R, mu, muA, beta0, sgga2, sgal2, agm, bgm, GinvsG2, insGRinsG) {
    invisible(.Call(`_MR_LDP_gibbs2_update_gamma`, gammah, Gammah, sg2, sG2, R, mu, muA, beta0, sgga2, sgal2, agm, bgm, GinvsG2, insGRinsG))
}

gibbs2_update_alpha <- function(gammah, Gammah, sg2, sG2, R, mu, muA, beta0, sgal2, GinvsG2) {
    invisible(.Call(`_MR_LDP_gibbs2_update_alpha`, gammah, Gammah, sg2, sG2, R, mu, muA, beta0, sgal2, GinvsG2))
}

Para_Gibbs1 <- function(F4Rblock, block_inf, nblocks, bh1, bh2, s12, s22, gamma, beta0, sgga2, coreNum) {
    invisible(.Call(`_MR_LDP_Para_Gibbs1`, F4Rblock, block_inf, nblocks, bh1, bh2, s12, s22, gamma, beta0, sgga2, coreNum))
}

Para_Gibbs2 <- function(F4Rblock, block_inf, nblocks, bh1, bh2, s12, s22, gamma, alpha, beta0, sgga2, sgal2, coreNum) {
    invisible(.Call(`_MR_LDP_Para_Gibbs2`, F4Rblock, block_inf, nblocks, bh1, bh2, s12, s22, gamma, alpha, beta0, sgga2, sgal2, coreNum))
}

gibbsres1 <- function(F4Rblock, block_inf, nblocks, bh1, bh2, s12, s22, gamma, beta0, sgga2, coreNum, IterMax) {
    .Call(`_MR_LDP_gibbsres1`, F4Rblock, block_inf, nblocks, bh1, bh2, s12, s22, gamma, beta0, sgga2, coreNum, IterMax)
}

gibbsres2 <- function(F4Rblock, block_inf, nblocks, bh1, bh2, s12, s22, gamma, alpha, beta0, sgga2, sgal2, coreNum, IterMax) {
    .Call(`_MR_LDP_gibbsres2`, F4Rblock, block_inf, nblocks, bh1, bh2, s12, s22, gamma, alpha, beta0, sgga2, sgal2, coreNum, IterMax)
}

Varres <- function(F4H2a, R, block_inf, nblocks, bh2, se2, N2) {
    invisible(.Call(`_MR_LDP_Varres`, F4H2a, R, block_inf, nblocks, bh2, se2, N2))
}

Herit_iMax <- function(R, block_inf, nblocks, bh2, se2, N2, ALres) {
    .Call(`_MR_LDP_Herit_iMax`, R, block_inf, nblocks, bh2, se2, N2, ALres)
}

heritability <- function(F4H2a, block_inf, nblocks, alpha) {
    .Call(`_MR_LDP_heritability`, F4H2a, block_inf, nblocks, alpha)
}

MRLDP_SimVb <- function(bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, R, constr, epsStopLogLik, maxIter, model) {
    .Call(`_MR_LDP_MRLDP_SimVb`, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, R, constr, epsStopLogLik, maxIter, model)
}

MRLDP_SimPXvb <- function(bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, R, constr, epsStopLogLik, maxIter, model) {
    .Call(`_MR_LDP_MRLDP_SimPXvb`, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, R, constr, epsStopLogLik, maxIter, model)
}

MRLDP_SimVBMg <- function(bh1, bh2, se1, se2, gamma, sgga2, sgal2, beta0, R, constr, epsStopLogLik, maxIter) {
    .Call(`_MR_LDP_MRLDP_SimVBMg`, bh1, bh2, se1, se2, gamma, sgga2, sgal2, beta0, R, constr, epsStopLogLik, maxIter)
}

MRLDP_SimMggibbs <- function(bh1, bh2, se1, se2, gamma, sgga2, sgal2, beta0, R, maxIter, agm, bgm) {
    .Call(`_MR_LDP_MRLDP_SimMggibbs`, bh1, bh2, se1, se2, gamma, sgga2, sgal2, beta0, R, maxIter, agm, bgm)
}

MRLDP_SimGibbspar <- function(R, block_inf, nblocks, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, IterMax, N2, model) {
    .Call(`_MR_LDP_MRLDP_SimGibbspar`, R, block_inf, nblocks, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, IterMax, N2, model)
}

MRLDP_RealVb <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model) {
    .Call(`_MR_LDP_MRLDP_RealVb`, bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model)
}

MRLDP_RealPXvb <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model) {
    .Call(`_MR_LDP_MRLDP_RealPXvb`, bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model)
}

MRLDP_RealPXvb_block <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model) {
    .Call(`_MR_LDP_MRLDP_RealPXvb_block`, bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model)
}

MRLDP_RealPXvb_par <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model) {
    .Call(`_MR_LDP_MRLDP_RealPXvb_par`, bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model)
}

MRLDP_RealParPXvb <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model) {
    .Call(`_MR_LDP_MRLDP_RealParPXvb`, bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model)
}

MRLDP_RealVBMg <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model) {
    .Call(`_MR_LDP_MRLDP_RealVBMg`, bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, beta0, sgga2, sgal2, coreNum, lam, constr, epsStopLogLik, maxIter, model)
}

MRLDP_RealMggibbs <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, beta0, sgga2, sgal2, coreNum, lam, maxIter, agm, bgm) {
    .Call(`_MR_LDP_MRLDP_RealMggibbs`, bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, beta0, sgga2, sgal2, coreNum, lam, maxIter, agm, bgm)
}

MRLDP_RealGibbspar <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, IterMax, N2, model) {
    .Call(`_MR_LDP_MRLDP_RealGibbspar`, bp, chr, avbIndex, idx4panel, block_file, stringname3, bh1, bh2, se1, se2, gamma, alpha, beta0, sgga2, sgal2, coreNum, lam, IterMax, N2, model)
}

Para_PXVb1 <- function(R, block_inf, nblocks, bh1, bh2, se1, se2, mu, beta0, sgga2, coreNum, constr, epsStopLogLik, maxIter) {
    .Call(`_MR_LDP_Para_PXVb1`, R, block_inf, nblocks, bh1, bh2, se1, se2, mu, beta0, sgga2, coreNum, constr, epsStopLogLik, maxIter)
}

Para_PXVb2 <- function(R, block_inf, nblocks, bh1, bh2, se1, se2, mu, muA, beta0, sgga2, sgal2, coreNum, constr, epsStopLogLik, maxIter) {
    .Call(`_MR_LDP_Para_PXVb2`, R, block_inf, nblocks, bh1, bh2, se1, se2, mu, muA, beta0, sgga2, sgal2, coreNum, constr, epsStopLogLik, maxIter)
}

blockinffun <- function(F4gammah) {
    .Call(`_MR_LDP_blockinffun`, F4gammah)
}

MRLDP_Real <- function(F4bh1, F4bh2, F4se1, F4se2, F4Rblock, model, constr, opts = NULL) {
    .Call(`_MR_LDP_MRLDP_Real`, F4bh1, F4bh2, F4se1, F4se2, F4Rblock, model, constr, opts)
}

PXvbfunM2_par <- function(F4Rblock, block_inf, nblocks, bh1, bh2, se1, se2, mu, muA, sgga2, sgal2, beta0, constr, epsStopLogLik, maxIter, coreNum) {
    .Call(`_MR_LDP_PXvbfunM2_par`, F4Rblock, block_inf, nblocks, bh1, bh2, se1, se2, mu, muA, sgga2, sgal2, beta0, constr, epsStopLogLik, maxIter, coreNum)
}

PXvbfunM1_par <- function(F4Rblock, block_inf, nblocks, bh1, bh2, se1, se2, mu, sgga2, beta0, constr, epsStopLogLik, maxIter, coreNum) {
    .Call(`_MR_LDP_PXvbfunM1_par`, F4Rblock, block_inf, nblocks, bh1, bh2, se1, se2, mu, sgga2, beta0, constr, epsStopLogLik, maxIter, coreNum)
}

vbfunM1 <- function(bh1, bh2, se1, se2, mu, sgga2, beta0, R, constr, epsStopLogLik, maxIter) {
    .Call(`_MR_LDP_vbfunM1`, bh1, bh2, se1, se2, mu, sgga2, beta0, R, constr, epsStopLogLik, maxIter)
}

PXvbfunM1 <- function(bh1, bh2, se1, se2, mu, sgga2, beta0, R, constr, epsStopLogLik, maxIter) {
    .Call(`_MR_LDP_PXvbfunM1`, bh1, bh2, se1, se2, mu, sgga2, beta0, R, constr, epsStopLogLik, maxIter)
}

vbfunM2 <- function(bh1, bh2, se1, se2, mu, muA, sgga2, sgal2, beta0, R, constr, epsStopLogLik, maxIter) {
    .Call(`_MR_LDP_vbfunM2`, bh1, bh2, se1, se2, mu, muA, sgga2, sgal2, beta0, R, constr, epsStopLogLik, maxIter)
}

PXvbfunM2 <- function(bh1, bh2, se1, se2, mu, muA, sgga2, sgal2, beta0, R, constr, epsStopLogLik, maxIter) {
    .Call(`_MR_LDP_PXvbfunM2`, bh1, bh2, se1, se2, mu, muA, sgga2, sgal2, beta0, R, constr, epsStopLogLik, maxIter)
}

VBMgM2 <- function(bh1, bh2, se1, se2, mu, sgga2, sgal2, beta0, R, constr, epsStopLogLik, maxIter) {
    .Call(`_MR_LDP_VBMgM2`, bh1, bh2, se1, se2, mu, sgga2, sgal2, beta0, R, constr, epsStopLogLik, maxIter)
}

MgMgib2 <- function(gammah, Gammah, sg2, sG2, mu, sgga2, sgal2, beta0, R, IterMax, agm, bgm) {
    .Call(`_MR_LDP_MgMgib2`, gammah, Gammah, sg2, sG2, mu, sgga2, sgal2, beta0, R, IterMax, agm, bgm)
}

PXvbfunM1_block <- function(F4Rblock, block_inf, nblocks, bh1, bh2, se1, se2, mu, sgga2, beta0, constr, epsStopLogLik, maxIter) {
    .Call(`_MR_LDP_PXvbfunM1_block`, F4Rblock, block_inf, nblocks, bh1, bh2, se1, se2, mu, sgga2, beta0, constr, epsStopLogLik, maxIter)
}

PXvbfunM2_block <- function(F4Rblock, block_inf, nblocks, bh1, bh2, se1, se2, mu, muA, sgga2, sgal2, beta0, constr, epsStopLogLik, maxIter) {
    .Call(`_MR_LDP_PXvbfunM2_block`, F4Rblock, block_inf, nblocks, bh1, bh2, se1, se2, mu, muA, sgga2, sgal2, beta0, constr, epsStopLogLik, maxIter)
}

getLineNum <- function(filename) {
    .Call(`_MR_LDP_getLineNum`, filename)
}

ReadSNPinfo <- function(stringname, A1, A2, rsname, chr, bp, morgan, N) {
    .Call(`_MR_LDP_ReadSNPinfo`, stringname, A1, A2, rsname, chr, bp, morgan, N)
}

Read_summarystat <- function(stringname, SA1, SA2, rsname, betah, s2, pvalue, chr, bp, N) {
    invisible(.Call(`_MR_LDP_Read_summarystat`, stringname, SA1, SA2, rsname, betah, s2, pvalue, chr, bp, N))
}

select <- function(vec_, idx_) {
    .Call(`_MR_LDP_select`, vec_, idx_)
}

matchsnp <- function(stringname1, stringname2, stringname3, matchExp) {
    .Call(`_MR_LDP_matchsnp`, stringname1, stringname2, stringname3, matchExp)
}

matchscreen <- function(screenname, stringname1, stringname2, stringname3, pva_cutoff, matchExp = FALSE) {
    .Call(`_MR_LDP_matchscreen`, screenname, stringname1, stringname2, stringname3, pva_cutoff, matchExp)
}

